export const CREATE_CAMPAIGN = 'FACEBOOK/CREATE_CAMPAIGN';
export const CREATE_CAMPAIGN_SUCCESS = 'FACEBOOK/CREATE_CAMPAIGN_SUCCESS';
export const GET_CAMPAIGN_LIST = 'FACEBOOK/GET_CAMPAIGN_LIST';
export const GET_CAMPAIGN_LIST_SUCCESS = 'FACEBOOK/GET_CAMPAIGN_LIST_SUCCESS';
export const UPDATE_CAMPAIGN = 'FACEBOOK/UPDATE_CAMPAIGN';
export const UPDATE_CAMPAIGN_SUCCESS = 'FACEBOOK/UPDATE_CAMPAIGN_SUCCESS';