export const CREATE_CAMPAIGN = 'FACEBOOK/CREATE_CAMPAIGN';
export const CREATE_CAMPAIGN_SUCCESS = 'FACEBOOK/CREATE_CAMPAIGN_SUCCESS';

export const GET_FACEBOOK_USER = 'FACEBOOK/GET_FACEBOOK_USER';
export const GET_FACEBOOK_USER_SUCCESS = 'FACEBOOK/GET_FACEBOOK_USER_SUCCESS';
export const GET_FACEBOOK_USER_FAILED = 'FACEBOOK/GET_FACEBOOK_USER_FAILED';

export const SAVE_FACEBOOK_CAMPAIGN = 'FACEBOOK/SAVE_FACEBOOK_CAMPAIGN';
export const SAVE_FACEBOOK_CAMPAIGN_SUCCESS = 'FACEBOOK/SAVE_FACEBOOK_CAMPAIGN_SUCCESS';

export const UPDATE_CAMPAIGN = 'FACEBOOK/UPDATE_CAMPAIGN';
export const UPDATE_CAMPAIGN_SUCCESS = 'FACEBOOK/UPDATE_CAMPAIGN_SUCCESS';

export const SAVE_FACEBOOK_USER = 'FACEBOOK/SAVE_FACEBOOK_USER';
export const SAVE_FACEBOOK_USER_SUCCESS = 'FACEBOOK/SAVE_FACEBOOK_USER_SUCCESS';

export const GET_FACEBOOK_AD_ACCOUNTS = 'FACEBOOK/GET_FACEBOOK_AD_ACCOUNTS';
export const GET_FACEBOOK_AD_ACCOUNTS_SUCCESS = 'FACEBOOK/GET_FACEBOOK_AD_ACCOUNTS_SUCCESS';

export const UPDATE_AD_ACCOUNT_CONNECTION = 'FACEBOOK/UPDATE_AD_ACCOUNT_CONNECTION';
export const UPDATE_AD_ACCOUNT_CONNECTION_SUCCESS = 'FACEBOOK/UPDATE_AD_ACCOUNT_CONNECTION_SUCCESS';

export const GET_FACEBOOK_CAMPAIGN_LIST = 'FACEBOOK/GET_FACEBOOK_CAMPAIGN_LIST';
export const GET_FACEBOOK_CAMPAIGN_LIST_SUCCESS = 'FACEBOOK/GET_FACEBOOK_CAMPAIGN_LIST_SUCCESS';
export const GET_FACEBOOK_CAMPAIGN_LIST_FAILED = 'FACEBOOK/GET_FACEBOOK_CAMPAIGN_LIST_FAILED';

export const UPDATE_FACEBOOK_CAMPAIGN = 'FACEBOOK/UPDATE_FACEBOOK_CAMPAIGN';
export const UPDATE_FACEBOOK_CAMPAIGN_SUCCESS = 'FACEBOOK/UPDATE_FACEBOOK_CAMPAIGN_SUCCESS';
export const UPDATE_FACEBOOK_CAMPAIGN_FAILED = 'FACEBOOK/UPDATE_FACEBOOK_CAMPAIGN_FAILED';

export const SAVE_FACEBOOK_AD_ACCOUNT = 'FACEBOOK/SAVE_FACEBOOK_AD_ACCOUNT';
export const SAVE_FACEBOOK_AD_ACCOUNT_SUCCESS = 'FACEBOOK/SAVE_FACEBOOK_AD_ACCOUNT_SUCCESS';

export const GET_FACEBOOK_PAGES = 'FACEBOOK/GET_FACEBOOK_PAGES';
export const GET_FACEBOOK_PAGES_SUCCESS = 'FACEBOOK/GET_FACEBOOK_PAGES_SUCCESS';

export const SAVE_FACEBOOK_PAGES_SETTINGS = 'FACEBOOK/SAVE_FACEBOOK_PAGES_SETTINGS';
export const SAVE_FACEBOOK_PAGES_SETTINGS_SUCCESS = 'FACEBOOK/SAVE_FACEBOOK_PAGES_SETTINGS_SUCCESS';

export const GET_FACEBOOK_CTA = 'FACEBOOK/GET_FACEBOOK_CTA';
export const GET_FACEBOOK_CTA_SUCCESS = 'FACEBOOK/GET_FACEBOOK_CTA_SUCCESS';

export const SEARCH_FACEBOOK_LOCATION = 'FACEBOOK/SEARCH_FACEBOOK_LOCATION';
export const SEARCH_FACEBOOK_LOCATION_SUCCESS = 'FACEBOOK/SEARCH_FACEBOOK_LOCATION_SUCCESS';

export const GET_AUDIENCE_SIZE = 'FACEBOOK/GET_AUDIENCE_SIZE';
export const GET_AUDIENCE_SIZE_SUCCESS = 'FACEBOOK/GET_AUDIENCE_SIZE_SUCCESS';

export const GET_AD_SET = 'FACEBOOK/GET_AD_SET'
export const GET_AD_SET_SUCCESS = 'FACEBOOK/GET_AD_SET_SUCCESS'
export const GET_AD_SET_FAIELD = 'FACEBOOK/GET_AD_SET_FAIELD'

export const DISCONNECT_ACCOUNT = 'FACEBOOK/DISCONNECT_ACCOUNT'
export const DISCONNECT_ACCOUNT_SUCCESS = 'FACEBOOK/DISCONNECT_ACCOUNT_SUCCESS'
export const DISCONNECT_ACCOUNT_FAIELD = 'FACEBOOK/DISCONNECT_ACCOUNT_FAIELD'

export const RESOLVED_UPDATING_TARGET_AUDIENCE = 'FACEBOOK/RESOLVED_UPDATING_TARGET_AUDIENCE'

// Campaign Reducer types
export const SAVE_CUSTOM_AUDIENCE = 'FACEBOOK/SAVE_CUSTOM_AUDIENCE';

export const SAVE_EXCLUDED_CUSTOM_AUDIENCE = 'FACEBOOK/SAVE_EXCLUDED_CUSTOM_AUDIENCE';

export const REMOVE_SELECTED_AUDIENCE = 'FACEBOOK/REMOVE_SELECTED_AUDIENCE';

export const REMOVE_EXCLUDED_AUDIENCE = 'FACEBOOK/REMOVE_EXCLUDED_AUDIENCE';

export const SHOW_PERSONAL_ATT_MODAL = 'FACEBOOK/SHOW_PERSONAL_ATT_MODAL';

export const ADD_PERSONAL_ATTRIBUTE = 'FACEBOOK/ADD_PERSONAL_ATTRIBUTE';

export const REMOVE_PERSONAL_ATTRIBUTE = 'FACEBOOK/REMOVE_PERSONAL_ATTRIBUTE';

export const ADD_CARD = 'FACEBOOK/ADD_CARD';

export const REMOVE_CARD = 'FACEBOOK/REMOVE_CARD';

export const ADD_OTHERS_TARGETING_PARAM = 'FACEBOOK/ADD_OTHERS_TARGETING_PARAM'

export const ADD_BUDGET_AND_SCHEDULE = 'FACEBOOK/ADD_BUDGET_AND_SCHEDULE'

export const UPLOAD_ADS_IMAGE = 'FACEBOOK/UPLOAD_ADS_IMAGE'
export const UPLOAD_ADS_IMAGE_SUCCESS = 'FACEBOOK/UPLOAD_ADS_IMAGE_SUCCESS'
export const REMOVE_ADS_IMAGE_SUCCESS = 'FACEBOOK/REMOVE_ADS_IMAGE_SUCCESS'

export const PUBLISH_AD = 'FACEBOOK/PUBLISH_AD'
export const PUBLISH_AD_SUCCESS = 'FACEBOOK/PUBLISH_AD_SUCCESS'
export const PUBLISH_AD_FAILED = 'FACEBOOK/PUBLISH_AD_FAILED'

export const UPDATE_IMAGE_FROM_CREATIVE = 'FACEBOOK/UPDATE_IMAGE_FROM_CREATIVE'

export const DELETE_MESSAGE = 'FACEBOOK/DELETE_MESSAGE'

export const SAVE_TARGETING_AUDIENCE = 'FACEBOOK/SAVE_TARGETING_AUDIENCE'

// Audience Targeting API types
export const GET_CUSTOM_AUDIENCE = 'FACEBOOK/GET_CUSTOM_AUDIENCE';
export const GET_CUSTOM_AUDIENCE_SUCCESS = 'FACEBOOK/GET_CUSTOM_AUDIENCE_SUCCESS';

export const GET_ALL_TARGET_CATEGORY = 'FACEBOOK/GET_ALL_TARGET_CATEGORY';
export const GET_ALL_TARGET_CATEGORY_SUCCESS = 'FACEBOOK/GET_ALL_TARGET_CATEGORY_SUCCESS';

export const SEARCH_INTEREST = 'FACEBOOK/SEARCH_INTEREST';
export const SEARCH_INTEREST_SUCCESS = 'FACEBOOK/SEARCH_INTEREST_SUCCESS';

export const BROWSE_BEHAVIOUR = 'FACEBOOK/BROWSE_BEHAVIOUR';
export const BROWSE_BEHAVIOUR_SUCCESS = 'FACEBOOK/BROWSE_BEHAVIOUR_SUCCESS';

export const BROWSE_INTEREST = 'FACEBOOK/BROWSE_INTEREST';
export const BROWSE_INTEREST_SUCCESS = 'FACEBOOK/BROWSE_INTEREST_SUCCESS';

export const SEARCH_SHCOOL = 'FACEBOOK/SEARCH_SHCOOL';
export const SEARCH_SHCOOL_SUCCESS = 'FACEBOOK/SEARCH_SHCOOL_SUCCESS';

export const SEARCH_EDUCATION_MAJOR = 'FACEBOOK/SEARCH_EDUCATION_MAJOR';
export const SEARCH_EDUCATION_MAJOR_SUCCESS = 'FACEBOOK/SEARCH_EDUCATION_MAJOR_SUCCESS';

export const SEARCH_WORK_EMPLOYER = 'FACEBOOK/SEARCH_WORK_EMPLOYER';
export const SEARCH_WORK_EMPLOYER_SUCCESS = 'FACEBOOK/SEARCH_WORK_EMPLOYER_SUCCESS';

export const SEARCH_JOB_TITLE = 'FACEBOOK/SEARCH_JOB_TITLE';
export const SEARCH_JOB_TITLE_SUCCESS = 'FACEBOOK/SEARCH_JOB_TITLE_SUCCESS';

export const BROWSE_INDUSTRIES = 'FACEBOOK/BROWSE_INDUSTRIES';
export const BROWSE_INDUSTRIES_SUCCESS = 'FACEBOOK/BROWSE_INDUSTRIES_SUCCESS';

export const BROWSE_DEMOGRAPHICS = 'FACEBOOK/BROWSE_DEMOGRAPHICS';
export const BROWSE_DEMOGRAPHICS_SUCCESS = 'FACEBOOK/BROWSE_DEMOGRAPHICS_SUCCESS';

export const BROWSE_LIFE_EVENTS = 'FACEBOOK/BROWSE_LIFE_EVENTS';
export const BROWSE_LIFE_EVENTS_SUCCESS = 'FACEBOOK/BROWSE_LIFE_EVENTS_SUCCESS';

export const BROWSE_INCOME = 'FACEBOOK/BROWSE_INCOME';
export const BROWSE_INCOME_SUCCESS = 'FACEBOOK/BROWSE_INCOME_SUCCESS';

export const BROWSE_FAMILY_STATUS = 'FACEBOOK/BROWSE_FAMILY_STATUS';
export const BROWSE_FAMILY_STATUS_SUCCESS = 'FACEBOOK/BROWSE_FAMILY_STATUS_SUCCESS';

export const BROWSE_USER_DEVICE = 'FACEBOOK/BROWSE_USER_DEVICE';
export const BROWSE_USER_DEVICE_SUCCESS = 'FACEBOOK/BROWSE_USER_DEVICE_SUCCESS';

export const BROWSE_OS = 'FACEBOOK/BROWSE_OS';
export const BROWSE_OS_SUCCESS = 'FACEBOOK/BROWSE_OS_SUCCESS';