version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb_ads
    environment: 
      - MONGO_INITDB_DATABASE=lead_generation
      - MONGO_INITDB_ROOT_USERNAME=raisul
      - MONGO_INITDB_ROOT_PASSWORD=redhat
    ports:
      - "27017:27017"

  ads_api:
    network_mode: host
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ads_api_image
    container_name: ads_api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  ads_ui:
    container_name: ads_ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: ads_ui_image
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/ads_ui
      - /ads_ui/node_modules
      - /ads_ui/build
