facebook_click_to_action = [
    {'name': 'Follow News Storyline', 'value': 'FOLLOW_NEWS_STORYLINE'}, 
    {'name': 'Get Directions', 'value': 'GET_DIRECTIONS'}, {'name': 'Moments', 'value': 'MOMENTS'}, 
    {'name': 'Install App', 'value': 'INSTALL_APP'}, {'name': 'Shop Now', 'value': 'SHOP_NOW'}, 
    {'name': 'Donate Now', 'value': 'DONATE_NOW'}, {'name': 'Follow Page', 'value': 'FOLLOW_PAGE'}, 
    {'name': 'Find A Group', 'value': 'FIND_A_GROUP'}, {'name': 'Get Offer', 'value': 'GET_OFFER'}, 
    {'name': 'Listen Music', 'value': 'LISTEN_MUSIC'}, {'name': 'Video Annotation', 'value': 'VIDEO_ANNOTATION'}, 
    {'name': 'Get Offer View', 'value': 'GET_OFFER_VIEW'}, {'name': 'Request Time', 'value': 'REQUEST_TIME'}, 
    {'name': 'Sell Now', 'value': 'SELL_NOW'}, {'name': 'Say Thanks', 'value': 'SAY_THANKS'}, 
    {'name': 'Refer Friends', 'value': 'REFER_FRIENDS'}, {'name': 'Share', 'value': 'SHARE'}, 
    {'name': 'Get Showtimes', 'value': 'GET_SHOWTIMES'}, {'name': 'Buy Now', 'value': 'BUY_NOW'}, 
    {'name': 'Use Mobile App', 'value': 'USE_MOBILE_APP'}, {'name': 'Order Now', 'value': 'ORDER_NOW'}, 
    {'name': 'Update App', 'value': 'UPDATE_APP'}, {'name': 'See More', 'value': 'SEE_MORE'}, 
    {'name': 'Book Travel', 'value': 'BOOK_TRAVEL'}, {'name': 'Sign Up', 'valu  e': 'SIGN_UP'}, 
    {'name': 'Send A Gift', 'value': 'SEND_A_GIFT'}, {'name': 'Swipe Up Shop', 'value': 'SWIPE_UP_SHOP'}, 
    {'name': 'Call Me', 'value': 'CALL_ME'}, {'name': 'No Button', 'value': 'NO_BUTTON'}, 
    {'name': 'Like Page', 'value': 'LIKE_PAGE'}, {'name': 'Buy', 'value': 'BUY'}, 
    {'name': 'Message Page', 'value': 'MESSAGE_PAGE'}, {'name': 'Contact', 'value': 'CONTACT'}, 
    {'name': 'Woodhenge Support', 'value': 'WOODHENGE_SUPPORT'}, {'name': 'Get Quote', 'value': 'GET_QUOTE'}, 
    {'name': 'Find Your Groups', 'value': 'FIND_YOUR_GROUPS'}, {'name': 'Watch More', 'value': 'WATCH_MORE'}, 
    {'name': 'Install Mobile App', 'value': 'INSTALL_MOBILE_APP'}, {'name': 'Add To Cart', 'value': 'ADD_TO_CART'}, 
    {'name': 'Mobile Download', 'value': 'MOBILE_DOWNLOAD'}, {'name': 'Listen Now', 'value': 'LISTEN_NOW'}, 
    {'name': 'Event Rsvp', 'value': 'EVENT_RSVP'}, {'name': 'Visit Pages Feed', 'value': 'VISIT_PAGES_FEED'}, 
    {'name': 'Watch Video', 'value': 'WATCH_VIDEO'}, {'name': 'Whatsapp Message', 'value': 'WHATSAPP_MESSAGE'}, 
    {'name': 'Play Game', 'value': 'PLAY_GAME'}, {'name': 'Download', 'value': 'DOWNLOAD'}, 
    {'name': 'Use App', 'value': 'USE_APP'}, {'name': 'Subscribe', 'value': 'SUBSCRIBE'}, 
    {'name': 'Follow User', 'value': 'FOLLOW_USER'}, {'name': 'Pay To Access', 'value': 'PAY_TO_ACCESS'}, 
    {'name': 'Donate', 'value': 'DONATE'}, {'name': 'Open Link', 'value': 'OPEN_LINK'}, 
    {'name': 'Contact Us', 'value': 'CONTACT_US'}, {'name': 'Record Now', 'value': 'RECORD_NOW'}, 
    {'name': 'Learn More', 'value': 'LEARN_MORE'}, {'name': 'Purchase Gift Cards', 'value': 'PURCHASE_GIFT_CARDS'}, 
    {'name': 'Sotto Subscribe', 'value': 'SOTTO_SUBSCRIBE'}, {'name': 'Buy Tickets', 'value': 'BUY_TICKETS'}, 
    {'name': 'Apply Now', 'value': 'APPLY_NOW'}, {'name': 'Call', 'value': 'CALL'}, 
    {'name': 'Swipe Up Product', 'value': 'SWIPE_UP_PRODUCT'}
] 