version: '3.7'

services:

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=dev.roboket.com
      - NGINX_PORT=80

networks:
   lead_generation: