version: '3.7'

services:

  lead_generation_ui:
    container_name: lead_generation_ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/ui'
      - '/ui/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
   lead_generation: