version: "3.7"
services:
  ads_ui:
    container_name: ads_ui
    build:
      context: .
      dockerfile: Dockerfile
    image: ads_ui_image
    stdin_open: true
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./:/ads_ui
      - /ads_ui/node_modules
      - /ads_ui/build
