version: '3.7'

services:
  ads_api:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: ads_api_image
    container_name: ads_api
    ports:
      - "8000:8000"
